# Generated by Django 5.1.4 on 2025-01-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0005_reclamations_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamations',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
