# Generated by Django 5.1.4 on 2024-12-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_custom_auth', '0002_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
