# Generated by Django 5.1.4 on 2024-12-27 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('is_like', models.BooleanField(default=False, verbose_name='É curtida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('like_dislike_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes_dislikes', to='contenttypes.contenttype', verbose_name='Curtida/Não curtida')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Interação',
                'verbose_name_plural': 'Interações',
                'unique_together': {('user', 'like_dislike_type', 'object_id')},
            },
        ),
    ]
