# Generated by Django 5.1.4 on 2025-01-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_alter_community_founded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
