# Generated by Django 5.1.4 on 2024-12-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0002_reclamations_user_alter_reclamations_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamations',
            name='dislike',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reclamations',
            name='like',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
