# Generated by Django 5.1.4 on 2024-12-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0003_reclamations_dislike_reclamations_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamations',
            name='responses_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
