# Generated by Django 5.1.4 on 2024-12-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0004_reclamations_responses_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamations',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
