# Generated by Django 5.1.4 on 2024-12-27 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('response', '0002_alter_response_content_type_alter_response_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['content_type', 'object_id'], name='response_re_content_eba467_idx'),
        ),
    ]
